version: '3.8'

services:
  verdaccio:
    image: "verdaccio/verdaccio:5"
    container_name: verdaccio
    env_file: 
      - .env
      - .env.local
    environment:
      VERDACCIO_PROTOCOL: https
      # DEBUG: verdaccio:*
    ports:
      - "4873:4873"
    volumes:
      - ./verdaccio/conf:/verdaccio/conf
      - ./verdaccio/plugins:/verdaccio/plugins
      - ./verdaccio/storage:/verdaccio/storage